[     UTC     ] Logs for admacademy.streamlit.app/

────────────────────────────────────────────────────────────────────────────────────────

[18:13:49] 🚀 Starting up repository: 'admacademy', branch: 'main', main module: 'app.py'

[18:13:49] 🐙 Cloning repository...

[18:13:49] 🐙 Cloning into '/mount/src/admacademy'...

[18:13:49] 🐙 Cloned repository!

[18:13:49] 🐙 Pulling code changes from Github...

[18:13:50] 📦 Processing dependencies...

Check if streamlit is installed

cat: /mount/admin/install_path: No such file or directory


──────────────────────────────── Installing Streamlit ──────────────────────────────────


Using uv pip install.

Using Python 3.13.3 environment at /home/adminuser/venv

Resolved 37 packages in 415ms

Prepared 37 packages in 2.06s

Installed 37 packages in 283ms

 + altair==5.5.0

 + attrs==25.3.0

 + blinker==1.9.0

 + cachetools==5.5.2

 + certifi==2025.4.26

 + charset-normalizer==3.4.2

 + click==8.2.1

 + gitdb==4.0.12

 + gitpython==3.1.44

 + idna[2025-06-01 18:13:53.346315] ==3.10

 + jinja2==3.1.6

 + jsonschema==4.24.0

 + jsonschema-specifications==2025.4.1

 + markupsafe==3.0.2

 + narwhals==1.41.0

 + numpy==2.2.6

 + packaging==24.2

 [2025-06-01 18:13:53.346568] + pandas==2.2.3

 + pillow==11.2.1

 + protobuf==6.31.1

 + pyarrow==20.0.0

 + pydeck==0.9.1

 + python-dateutil==2.9.0.post0

 + pytz==2025.2

 + referencing==0.36.2

 + requests==2.32.3

 + rpds-py==0.25.1[2025-06-01 18:13:53.346766] 

 + six==1.17.0

 + smmap==5.0.2

 + streamlit==1.45.1

 + tenacity==9.1.2

 + toml==0.10.2

 + tornado==6.5.1

 + typing-extensions[2025-06-01 18:13:53.347121] ==4.13.2

 + tzdata==2025.2

 + urllib3==2.4.0

 + watchdog==6.0.0


────────────────────────────────────────────────────────────────────────────────────────


[18:13:54] 📦 Processed dependencies!

cat: /mount/admin/install_path: No such file or directory




2025-06-01 18:14:14.091 Uncaught app execution

Traceback (most recent call last):

  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling

    result = func()

  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 645, in code_to_exec

    exec(code, module.__dict__)

    ~~~~^^^^^^^^^^^^^^^^^^^^^^^

  File "/mount/src/admacademy/app.py", line 421, in <module>

    st.markdown(f"<div class='metric-value'>{user['progress']['trails_completed']}/5</div>", unsafe_allow_html=True)

                                             ~~~~^^^^^^^^^^^^

KeyError: 'progress'

[18:14:24] 🐙 Pulling code changes from Github...

[18:14:25] 📦 Processing dependencies...

[18:14:25] 📦 Processed dependencies!

[18:14:28] 🔄 Updated app!

[18:20:15] 🐙 Pulling code changes from Github...

[18:20:16] 📦 Processing dependencies...

2025-06-01 18:20:16.432 Uncaught app execution

Traceback (most recent call last):

  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling

    result = func()

  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 645, in code_to_exec

    exec(code, module.__dict__)

    ~~~~^^^^^^^^^^^^^^^^^^^^^^^

  File "/mount/src/admacademy/app.py", line 500, in <module>

    import plotly.express as px

ModuleNotFoundError: No module named 'plotly'


──────────────────────────────────────── uv ───────────────────────────────────────────


Using uv pip install.

Using Python 3.13.3 environment at /home/adminuser/venv

Resolved 52 packages in 326ms

  × Failed to download and build `pandas==2.1.0`

  ╰─▶ Build backend failed to build wheel through `build_wheel` (exit status:

      1)


      [stdout]

      + meson setup

      /home/adminuser/.cache/uv/sdists-v6/pypi/pandas/2.1.0/24_E8Vy_u96ZbaEV3GufS/src

      /home/adminuser/.cache/uv/sdists-v6/pypi/pandas/2.1.0/24_E8Vy_u96ZbaEV3GufS/src/.mesonpy-0f_amvqi/build

      -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --vsenv

      --native-file=/home/adminuser/.cache/uv/sdists-v6/pypi/pandas/2.1.0/24_E8Vy_u96ZbaEV3GufS/src/.mesonpy-0f_amvqi/build/meson-python-native-file.ini

      The Meson build system

      Version: 1.0.1

      Source dir:

      /home/adminuser/.cache/uv/sdists-v6/pypi/pandas/2.1.0/24_E8Vy_u96ZbaEV3GufS/src

      Build dir:

      /home/adminuser/.cache/uv/sdists-v6/pypi/pandas/2.1.0/24_E8Vy_u96ZbaEV3GufS/src/.mesonpy-0f_amvqi/build

      Build type: native build

      Project name: pandas

      Project version: 2.1.0

      C compiler for the host machine: cc (gcc 10.2.1 "cc (Debian 10.2.1-6)

      10.2.1 20210110")

      C linker for the host machine: cc ld.bfd 2.35.2

      C++ compiler for the host machine: c++ (gcc 10.2.1 "c++ (Debian

      10.2.1-6) 10.2.1 20210110")

      C++ linker for the host machine: c++ ld.bfd 2.35.2

      Cython compiler for the host machine: cython (cython 0.29.37)

      Host machine cpu family: x86_64

      Host machine cpu: x86_64

      Program python found: YES

      (/home/adminuser/.cache/uv/builds-v0/.tmpnu4CRa/bin/python)

      Did not find pkg-config by name 'pkg-config'

      Found Pkg-config: NO

      Build targets in project: 53


      pandas 2.1.0


        User defined options

          Native files:

      /home/adminuser/.cache/uv/sdists-v6/pypi/pandas/2.1.0/24_E8Vy_u96ZbaEV3GufS/src/.mesonpy-0f_amvqi/build/meson-python-native-file.ini

          buildtype   : release

          b_ndebug    : if-release

          b_vscrt     : md


      Found ninja-1.11.1.git.kitware.jobserver-1 at

      /home/adminuser/.cache/uv/builds-v0/.tmpnu4CRa/bin/ninja

      + /home/adminuser/.cache/uv/builds-v0/.tmpnu4CRa/bin/ninja

      [1/151] Generating pandas/_libs/hashtable_func_helper_pxi with a custom

      command

      [2/151] Generating pandas/_libs/khash_primitive_helper_pxi with a custom

      command

      [3/151] Generating pandas/__init__.py with a custom command

      [4/151] Generating pandas/_libs/hashtable_class_helper_pxi with a custom

      command

      [5/151] Generating pandas/_libs/index_class_helper_pxi with a custom

      command

      [6/151] Generating pandas/_libs/algos_take_helper_pxi with a custom

      command

      [7/151] Generating pandas/_libs/algos_common_helper_pxi with a custom

      command

      [8/151] Generating pandas/_libs/intervaltree_helper_pxi with a custom

      command

      [9/151] Generating pandas/_libs/sparse_op_helper_pxi with a custom

      command

      [10/151] Compiling C object

      pandas/_libs/tslibs/parsing.cpython-313-x86_64-linux-gnu.so.p/.._src_parser_tokenizer.c.o

      [11/151] Compiling Cython source

      /home/adminuser/.cache/uv/sdists-v6/pypi/pandas/2.1.0/24_E8Vy_u96ZbaEV3GufS/src/pandas/_libs/tslibs/base.pyx

      [12/151] Compiling C object

      pandas/_libs/tslibs/base.cpython-313-x86_64-linux-gnu.so.p/meson-generated_pandas__libs_tslibs_base.pyx.c.o

      FAILED:

      pandas/_libs/tslibs/base.cpython-313-x86_64-linux-gnu.so.p/meson-generated_pandas__libs_tslibs_base.pyx.c.o

      cc -Ipandas/_libs/tslibs/base.cpython-313-x86_64-linux-gnu.so.p

      -Ipandas/_libs/tslibs -I../../pandas/_libs/tslibs

      -I../../../../../../../../builds-v0/.tmpnu4CRa/lib/python3.13/site-packages/numpy/_core/include

      -I../../pandas/_libs/include -I/usr/local/include/python3.13

      -fvisibility=hidden -fdiagnostics-color=always -DNDEBUG

      -D_FILE_OFFSET_BITS=64 -w -std=c99 -O3 -DNPY_NO_DEPRECATED_API=0

      -DNPY_TARGET_VERSION=NPY_1_21_API_VERSION -fPIC -MD -MQ

      pandas/_libs/tslibs/base.cpython-313-x86_64-linux-gnu.so.p/meson-generated_pandas__libs_tslibs_base.pyx.c.o

      -MF

      pandas/_libs/tslibs/base.cpython-313-x86_64-linux-gnu.so.p/meson-generated_pandas__libs_tslibs_base.pyx.c.o.d

      -o

      pandas/_libs/tslibs/base.cpython-313-x86_64-linux-gnu.so.p/meson-generated_pandas__libs_tslibs_base.pyx.c.o

      -c

      pandas/_libs/tslibs/base.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/base.pyx.c

      pandas/_libs/tslibs/base.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/base.pyx.c:

      In function ‘__Pyx_PyInt_As_long’:

      pandas/_libs/tslibs/base.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/base.pyx.c:5397:27:

      error: too few arguments to function ‘_PyLong_AsByteArray’

       5397 |                 int ret = _PyLong_AsByteArray((PyLongObject *)v,

            |                           ^~~~~~~~~~~~~~~~~~~

      In file included from /usr/local/include/python3.13/longobject.h:107,

                       from /usr/local/include/python3.13/Python.h:81,

                       from

      pandas/_libs/tslibs/base.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/base.pyx.c:6:

      /usr/local/include/python3.13/cpython/longobject.h:111:17: note:

      declared here

        111 | PyAPI_FUNC(int) _PyLong_AsByteArray(PyLongObject* v,

            |                 ^~~~~~~~~~~~~~~~~~~

      pandas/_libs/tslibs/base.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/base.pyx.c:

      In function ‘__Pyx_PyInt_As_int’:

      pandas/_libs/tslibs/base.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/base.pyx.c:5631:27:

      error: too few arguments to function ‘_PyLong_AsByteArray’

       5631 |                 int ret = _PyLong_AsByteArray((PyLongObject *)v,

            |                           ^~~~~~~~~~~~~~~~~~~

      In file included from /usr/local/include/python3.13/longobject.h:107,

                       from /usr/local/include/python3.13/Python.h:81,

                       from

      pandas/_libs/tslibs/base.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/base.pyx.c:6:

      /usr/local/include/python3.13/cpython/longobject.h:111:17: note:

      declared here

        111 | PyAPI_FUNC(int) _PyLong_AsByteArray(PyLongObject* v,

            |                 ^~~~~~~~~~~~~~~~~~~

      [13/151] Compiling Cython source

      /home/adminuser/.cache/uv/sdists-v6/pypi/pandas/2.1.0/24_E8Vy_u96ZbaEV3GufS/src/pandas/_libs/tslibs/nattype.pyx

      [14/151] Compiling Cython source

      /home/adminuser/.cache/uv/sdists-v6/pypi/pandas/2.1.0/24_E8Vy_u96ZbaEV3GufS/src/pandas/_libs/tslibs/ccalendar.pyx

      [15/151] Compiling Cython source

      /home/adminuser/.cache/uv/sdists-v6/pypi/pandas/2.1.0/24_E8Vy_u96ZbaEV3GufS/src/pandas/_libs/tslibs/dtypes.pyx

      [16/151] Compiling Cython source

      /home/adminuser/.cache/uv/sdists-v6/pypi/pandas/2.1.0/24_E8Vy_u96ZbaEV3GufS/src/pandas/_libs/tslibs/np_datetime.pyx

      [17/151] Compiling Cython source

      /home/adminuser/.cache/uv/sdists-v6/pypi/pandas/2.1.0/24_E8Vy_u96ZbaEV3GufS/src/pandas/_libs/arrays.pyx

      [18/151] Compiling Cython source

      /home/adminuser/.cache/uv/sdists-v6/pypi/pandas/2.1.0/24_E8Vy_u96ZbaEV3GufS/src/pandas/_libs/tslibs/strptime.pyx

      [19/151] Compiling Cython source

      /home/adminuser/.cache/uv/sdists-v6/pypi/pandas/2.1.0/24_E8Vy_u96ZbaEV3GufS/src/pandas/_libs/tslibs/vectorized.pyx

      [20/151] Compiling Cython source

      /home/adminuser/.cache/uv/sdists-v6/pypi/pandas/2.1.0/24_E8Vy_u96ZbaEV3GufS/src/pandas/_libs/tslibs/timezones.pyx

      [21/151] Compiling Cython source

      /home/adminuser/.cache/uv/sdists-v6/pypi/pandas/2.1.0/24_E8Vy_u96ZbaEV3GufS/src/pandas/_libs/tslibs/tzconversion.pyx

      [22/151] Compiling Cython source

      /home/adminuser/.cache/uv/sdists-v6/pypi/pandas/2.1.0/24_E8Vy_u96ZbaEV3GufS/src/pandas/_libs/tslibs/fields.pyx

      [23/151] Compiling Cython source

      /home/adminuser/.cache/uv/sdists-v6/pypi/pandas/2.1.0/24_E8Vy_u96ZbaEV3GufS/src/pandas/_libs/tslibs/conversion.pyx

      [24/151] Compiling Cython source

      /home/adminuser/.cache/uv/sdists-v6/pypi/pandas/2.1.0/24_E8Vy_u96ZbaEV3GufS/src/pandas/_libs/tslibs/period.pyx

      [25/151] Compiling Cython source

      /home/adminuser/.cache/uv/sdists-v6/pypi/pandas/2.1.0/24_E8Vy_u96ZbaEV3GufS/src/pandas/_libs/tslibs/offsets.pyx

      [26/151] Compiling Cython source

      /home/adminuser/.cache/uv/sdists-v6/pypi/pandas/2.1.0/24_E8Vy_u96ZbaEV3GufS/src/pandas/_libs/tslibs/parsing.pyx

      [27/151] Compiling Cython source

      /home/adminuser/.cache/uv/sdists-v6/pypi/pandas/2.1.0/24_E8Vy_u96ZbaEV3GufS/src/pandas/_libs/tslibs/timestamps.pyx

      [28/151] Compiling Cython source

      /home/adminuser/.cache/uv/sdists-v6/pypi/pandas/2.1.0/24_E8Vy_u96ZbaEV3GufS/src/pandas/_libs/tslibs/timedeltas.pyx

      [29/151] Compiling Cython source

      /home/adminuser/.cache/uv/sdists-v6/pypi/pandas/2.1.0/24_E8Vy_u96ZbaEV3GufS/src/pandas/_libs/algos.pyx

      ninja: build stopped: subcommand failed.


Checking if Streamlit is installed

Found Streamlit version 1.45.1 in the environment

Installing rich for an improved exception logging

Using uv pip install.

Using Python 3.13.3 environment at /home/adminuser/venv

Resolved 4 packages in 43ms

Prepared 1 package in 42ms

Installed 4 packages in 18ms

 + markdown-it-py==3.0.0

 + mdurl==0.1.2

 + pygments[2025-06-01 18:20:41.560532] ==2.19.1

 + rich==14.0.0


────────────────────────────────────────────────────────────────────────────────────────



──────────────────────────────────────── pip ───────────────────────────────────────────


Using standard pip install.

────────────────────── Traceback (most recent call last) ───────────────────────

  /home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptru  

  nner/exec_code.py:121 in exec_func_with_error_handling                        

                                                                                

  /home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptru  

  nner/script_runner.py:645 in code_to_exec                                     

                                                                                

  /mount/src/admacademy/app.py:500 in <module>                                  

                                                                                

    497 │   │   completed_simulations = [sim for sim in simulations if sim['co  

    498 │   │                                                                   

    499 │   │   # Criar dados para o gráfico                                    

  ❱ 500 │   │   import plotly.express as px                                     

    501 │   │   import pandas as pd                                             

    502 │   │                                                                   

    503 │   │   if completed_simulations:                                       

────────────────────────────────────────────────────────────────────────────────

ModuleNotFoundError: No module named 'plotly'

Collecting streamlit==1.31.0 (from -r /mount/src/admacademy/requirements.txt (line 1))

  Downloading streamlit-1.31.0-py2.py3-none-any.whl.metadata (8.1 kB)

Collecting pandas==2.1.0 (from -r /mount/src/admacademy/requirements.txt (line 2))

  Downloading pandas-2.1.0.tar.gz (4.3 MB)

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 MB 58.2 MB/s eta 0:00:00[2025-06-01 18:20:43.337966] 

  Installing build dependencies: started

  Installing build dependencies: finished with status 'done'

  Getting requirements to build wheel: started

  Getting requirements to build wheel: finished with status 'done'

  Installing backend dependencies: started

  Installing backend dependencies: finished with status 'done'

  Preparing metadata (pyproject.toml): started

────────────────────── Traceback (most recent call last) ───────────────────────

  /home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptru  

  nner/exec_code.py:121 in exec_func_with_error_handling                        

                                                                                

  /home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptru  

  nner/script_runner.py:645 in code_to_exec                                     

                                                                                

  /mount/src/admacademy/app.py:500 in <module>                                  

                                                                                

    497 │   │   completed_simulations = [sim for sim in simulations if sim['co  

    498 │   │                                                                   

    499 │   │   # Criar dados para o gráfico                                    

  ❱ 500 │   │   import plotly.express as px                                     

    501 │   │   import pandas as pd                                             

    502 │   │                                                                   

    503 │   │   if completed_simulations:                                       

────────────────────────────────────────────────────────────────────────────────

ModuleNotFoundError: No module named 'plotly'

────────────────────── Traceback (most recent call last) ───────────────────────

  /home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptru  

  nner/exec_code.py:121 in exec_func_with_error_handling                        

                                                                                

  /home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptru  

  nner/script_runner.py:645 in code_to_exec                                     

                                                                                

  /mount/src/admacademy/app.py:614 in <module>                                  

                                                                                

    611 │                                                                       

    612 │   if completed_simulations:                                           

    613 │   │   # Criar dados para o gráfico                                    

  ❱ 614 │   │   import plotly.express as px                                     

    615 │   │   import pandas as pd                                             

    616 │   │                                                                   

    617 │   │   df = pd.DataFrame(completed_simulations)                        

────────────────────────────────────────────────────────────────────────────────

ModuleNotFoundError: No module named 'plotly'

  Preparing metadata (pyproject.toml): finished with status 'error'

  error: subprocess-exited-with-error

  

  × Preparing metadata (pyproject.toml) did not run successfully.

  │ exit code: 1

  ╰─> [105 lines of output]

      + meson setup /tmp/pip-install-i88g7ls3/pandas_530747d5030845c1aca2e6e690d68395 /tmp/pip-install-i88g7ls3/pandas_530747d5030845c1aca2e6e690d68395/.mesonpy-923y4et5/build -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --vsenv --native-file=/tmp/pip-install-i88g7ls3/pandas_530747d5030845c1aca2e6e690d68395/.mesonpy-923y4et5/build/meson-python-native-file.ini

      The Meson build system

      Version: 1.0.1

      Source dir: /tmp/pip-install-i88g7ls3/pandas_530747d5030845c1aca2e6e690d68395

      Build dir: /tmp/pip-install-i88g7ls3/pandas_530747d5030845c1aca2e6e690d68395/.mesonpy-923y4et5/build

      Build type: native build

      Project name: pandas

      Project version: 2.1.0

      C compiler for the host machine: cc (gcc 10.2.1 "cc (Debian 10.2.1-6) 10.2.1 20210110")

      C linker for the host machine: cc ld.bfd 2.35.2

      C++ compiler for the host machine: c++ (gcc 10.2.1 "c++ (Debian 10.2.1-6) 10.2.1 20210110")

      C++ linker for the host machine: c++ ld.bfd 2.35.2

      Cython compiler for the host machine: cython (cython 0.29.37)

      Host machine cpu family: x86_64

      Host machine cpu: x86_64

      Program python found: YES (/home/adminuser/venv/bin/python)

      Did not find pkg-config by name 'pkg-config'

      Found Pkg-config: NO

      Build targets in project: 53

      

      pandas 2.1.0

      

        User defined options

          Native files: /tmp/pip-install-i88g7ls3/pandas_530747d5030845c1aca2e6e690d68395/.mesonpy-923y4et5/build/meson-python-native-file.ini

          buildtype   : release

          b_ndebug    : if-release

          b_vscrt     : md

      

      Found ninja-1.11.1.git.kitware.jobserver-1 at /tmp/pip-build-env-t2qftrf6/normal/bin/ninja

      + /tmp/pip-build-env-t2qftrf6/normal/bin/ninja

      [1/151] Generating pandas/_libs/index_class_helper_pxi with a custom command

      [2/151] Generating pandas/_libs/hashtable_func_helper_pxi with a custom command

      [3/151] Generating pandas/_libs/algos_common_helper_pxi with a custom command

      [4/151] Generating pandas/_libs/intervaltree_helper_pxi with a custom command

      [5/151] Generating pandas/_libs/hashtable_class_helper_pxi with a custom command

      [6/151] Generating pandas/_libs/khash_primitive_helper_pxi with a custom command

      [7/151] Generating pandas/__init__.py with a custom command

      [8/151] Generating pandas/_libs/algos_take_helper_pxi with a custom command

      [9/151] Generating pandas/_libs/sparse_op_helper_pxi with a custom command

      [10/151] Compiling C object pandas/_libs/tslibs/parsing.cpython-313-x86_64-linux-gnu.so.p/.._src_parser_tokenizer.c.o

      [11/151] Compiling Cython source /tmp/pip-install-i88g7ls3/pandas_530747d5030845c1aca2e6e690d68395/pandas/_libs/tslibs/base.pyx

      [12/151] Compiling Cython source /tmp/pip-install-i88g7ls3/pandas_530747d5030845c1aca2e6e690d68395/pandas/_libs/tslibs/ccalendar.pyx

      [13/151] Compiling C object pandas/_libs/tslibs/base.cpython-313-x86_64-linux-gnu.so.p/meson-generated_pandas__libs_tslibs_base.pyx.c.o

      FAILED: pandas/_libs/tslibs/base.cpython-313-x86_64-linux-gnu.so.p/meson-generated_pandas__libs_tslibs_base.pyx.c.o

      cc -Ipandas/_libs/tslibs/base.cpython-313-x86_64-linux-gnu.so.p -Ipandas/_libs/tslibs -I../../pandas/_libs/tslibs -I../../../../pip-build-env-t2qftrf6/overlay/lib/python3.13/site-packages/numpy/_core/include -I../../pandas/_libs/include -I/usr/local/include/python3.13 -fvisibility=hidden -fdiagnostics-color=always -DNDEBUG -D_FILE_OFFSET_BITS=64 -w -std=c99 -O3 -DNPY_NO_DEPRECATED_API=0 -DNPY_TARGET_VERSION=NPY_1_21_API_VERSION -fPIC -MD -MQ pandas/_libs/tslibs/base.cpython-313-x86_64-linux-gnu.so.p/meson-generated_pandas__libs_tslibs_base.pyx.c.o -MF pandas/_libs/tslibs/base.cpython-313-x86_64-linux-gnu.so.p/meson-generated_pandas__libs_tslibs_base.pyx.c.o.d -o pandas/_libs/tslibs/base.cpython-313-x86_64-linux-gnu.so.p/meson-generated_pandas__libs_tslibs_base.pyx.c.o -c pandas/_libs/tslibs/base.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/base.pyx.c

      pandas/_libs/tslibs/base.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/base.pyx.c: In function ‘__Pyx_PyInt_As_long’:

      pandas/_libs/tslibs/base.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/base.pyx.c:5397:27: error: too few arguments to function ‘_PyLong_AsByteArray’

       5397 |                 int ret = _PyLong_AsByteArray((PyLongObject *)v,

            |                           ^~~~~~~~~~~~~~~~~~~

      In file included from /usr/local/include/python3.13/longobject.h:107,

                       from /usr/local/include/python3.13/Python.h:81,

                       from pandas/_libs/tslibs/base.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/base.pyx.c:6:

      /usr/local/include/python3.13/cpython/longobject.h:111:17: note: declared here

        111 | PyAPI_FUNC(int) _PyLong_AsByteArray(PyLongObject* v,

            |                 ^~~~~~~~~~~~~~~~~~~

      pandas/_libs/tslibs/base.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/base.pyx.c: In function ‘__Pyx_PyInt_As_int’:

      pandas/_libs/tslibs/base.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/base.pyx.c:5631:27: error: too few arguments to function ‘_PyLong_AsByteArray’

       5631 |                 int ret = _PyLong_AsByteArray((PyLongObject *)v,

            |                           ^~~~~~~~~~~~~~~~~~~

      In file included from /usr/local/include/python3.13/longobject.h:107,

                       from /usr/local/include/python3.13/Python.h:81,

                       from pandas/_libs/tslibs/base.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/base.pyx.c:6:

      /usr/local/include/python3.13/cpython/longobject.h:111:17: note: declared here

        111 | PyAPI_FUNC(int) _PyLong_AsByteArray(PyLongObject* v,

            |                 ^~~~~~~~~~~~~~~~~~~

      [14/151] Compiling C object pandas/_libs/tslibs/ccalendar.cpython-313-x86_64-linux-gnu.so.p/meson-generated_pandas__libs_tslibs_ccalendar.pyx.c.o

      FAILED: pandas/_libs/tslibs/ccalendar.cpython-313-x86_64-linux-gnu.so.p/meson-generated_pandas__libs_tslibs_ccalendar.pyx.c.o

      cc -Ipandas/_libs/tslibs/ccalendar.cpython-313-x86_64-linux-gnu.so.p -Ipandas/_libs/tslibs -I../../pandas/_libs/tslibs -I../../../../pip-build-env-t2qftrf6/overlay/lib/python3.13/site-packages/numpy/_core/include -I../../pandas/_libs/include -I/usr/local/include/python3.13 -fvisibility=hidden -fdiagnostics-color=always -DNDEBUG -D_FILE_OFFSET_BITS=64 -w -std=c99 -O3 -DNPY_NO_DEPRECATED_API=0 -DNPY_TARGET_VERSION=NPY_1_21_API_VERSION -fPIC -MD -MQ pandas/_libs/tslibs/ccalendar.cpython-313-x86_64-linux-gnu.so.p/meson-generated_pandas__libs_tslibs_ccalendar.pyx.c.o -MF pandas/_libs/tslibs/ccalendar.cpython-313-x86_64-linux-gnu.so.p/meson-generated_pandas__libs_tslibs_ccalendar.pyx.c.o.d -o pandas/_libs/tslibs/ccalendar.cpython-313-x86_64-linux-gnu.so.p/meson-generated_pandas__libs_tslibs_ccalendar.pyx.c.o -c pandas/_libs/tslibs/ccalendar.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/ccalendar.pyx.c

      pandas/_libs/tslibs/ccalendar.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/ccalendar.pyx.c: In function ‘__Pyx_PyInt_As_int’:

      pandas/_libs/tslibs/ccalendar.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/ccalendar.pyx.c:7550:27: error: too few arguments to function ‘_PyLong_AsByteArray’

       7550 |                 int ret = _PyLong_AsByteArray((PyLongObject *)v,

            |                           ^~~~~~~~~~~~~~~~~~~

      In file included from /usr/local/include/python3.13/longobject.h:107,

                       from /usr/local/include/python3.13/Python.h:81,

                       from pandas/_libs/tslibs/ccalendar.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/ccalendar.pyx.c:6:

      /usr/local/include/python3.13/cpython/longobject.h:111:17: note: declared here

        111 | PyAPI_FUNC(int) _PyLong_AsByteArray(PyLongObject* v,

            |                 ^~~~~~~~~~~~~~~~~~~

      pandas/_libs/tslibs/ccalendar.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/ccalendar.pyx.c: In function ‘__Pyx_PyInt_As_long’:

      pandas/_libs/tslibs/ccalendar.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/ccalendar.pyx.c:7860:27: error: too few arguments to function ‘_PyLong_AsByteArray’

       7860 |                 int ret = _PyLong_AsByteArray((PyLongObject *)v,

            |                           ^~~~~~~~~~~~~~~~~~~

      In file included from /usr/local/include/python3.13/longobject.h:107,

                       from /usr/local/include/python3.13/Python.h:81,

                       from pandas/_libs/tslibs/ccalendar.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/ccalendar.pyx.c:6:

      /usr/local/include/python3.13/cpython/longobject.h:111:17: note: declared here

        111 | PyAPI_FUNC(int) _PyLong_AsByteArray(PyLongObject* v,

            |                 ^~~~~~~~~~~~~~~~~~~

      [15/151] Compiling Cython source /tmp/pip-install-i88g7ls3/pandas_530747d5030845c1aca2e6e690d68395/pandas/_libs/tslibs/dtypes.pyx

      [16/151] Compiling Cython source /tmp/pip-install-i88g7ls3/pandas_530747d5030845c1aca2e6e690d68395/pandas/_libs/tslibs/np_datetime.pyx

      [17/151] Compiling Cython source /tmp/pip-install-i88g7ls3/pandas_530747d5030845c1aca2e6e690d68395/pandas/_libs/tslibs/nattype.pyx

      [18/151] Compiling Cython source /tmp/pip-install-i88g7ls3/pandas_530747d5030845c1aca2e6e690d68395/pandas/_libs/arrays.pyx

      [19/151] Compiling Cython source /tmp/pip-install-i88g7ls3/pandas_530747d5030845c1aca2e6e690d68395/pandas/_libs/tslibs/conversion.pyx

      [20/151] Compiling Cython source /tmp/pip-install-i88g7ls3/pandas_530747d5030845c1aca2e6e690d68395/pandas/_libs/tslibs/tzconversion.pyx

      [21/151] Compiling Cython source /tmp/pip-install-i88g7ls3/pandas_530747d5030845c1aca2e6e690d68395/pandas/_libs/tslibs/vectorized.pyx

      [22/151] Compiling Cython source /tmp/pip-install-i88g7ls3/pandas_530747d5030845c1aca2e6e690d68395/pandas/_libs/tslibs/parsing.pyx

      [23/151] Compiling Cython source /tmp/pip-install-i88g7ls3/pandas_530747d5030845c1aca2e6e690d68395/pandas/_libs/tslibs/timezones.pyx

      [24/151] Compiling Cython source /tmp/pip-install-i88g7ls3/pandas_530747d5030845c1aca2e6e690d68395/pandas/_libs/tslibs/fields.pyx

      [25/151] Compiling Cython source /tmp/pip-install-i88g7ls3/pandas_530747d5030845c1aca2e6e690d68395/pandas/_libs/tslibs/offsets.pyx

      [26/151] Compiling Cython source /tmp/pip-install-i88g7ls3/pandas_530747d5030845c1aca2e6e690d68395/pandas/_libs/tslibs/timedeltas.pyx

      [27/151] Compiling Cython source /tmp/pip-install-i88g7ls3/pandas_530747d5030845c1aca2e6e690d68395/pandas/_libs/tslibs/strptime.pyx

      [28/151] Compiling Cython source /tmp/pip-install-i88g7ls3/pandas_530747d5030845c1aca2e6e690d68395/pandas/_libs/tslibs/timestamps.pyx

      [29/151] Compiling Cython source /tmp/pip-install-i88g7ls3/pandas_530747d5030845c1aca2e6e690d68395/pandas/_libs/tslibs/period.pyx

      [30/151] Compiling Cython source /tmp/pip-install-i88g7ls3/pandas_530747d5030845c1aca2e6e690d68395/pandas/_libs/algos.pyx

      ninja: build stopped: subcommand failed.

      [end of output]

  

  note: This error originates from a subprocess, and is likely not a problem with pip.

error: metadata-generation-failed


× Encountered error while generating package metadata.

╰─> See above for output.


note: This is an issue with the package mentioned above, not pip.

hint: See above for details.


[notice] A new release of pip is available: 24.0 -> 25.1.1

[notice] To update, run: pip install --upgrade pip

Checking if Streamlit is installed

Found Streamlit version 1.45.1 in the environment

Installing rich for an improved exception logging

Using standard pip install.

Collecting rich>=10.14.0

  Downloading rich-14.0.0-py3-none-any.whl.metadata (18 kB)

Collecting markdown-it-py>=2.2.0 (from rich>=10.14.0)

  Downloading markdown_it_py-3.0.0-py3-none-any.whl.metadata (6.9 kB)

Collecting pygments<3.0.0,>=2.13.0 (from rich>=10.14.0)

  Downloading pygments-2.19.1-py3-none-any.whl.metadata (2.5 kB)

Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich>=10.14.0)

  Downloading mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)

Downloading rich-14.0.0-py3-none-any.whl (243 kB)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 243.2/243.2 kB 10.8 MB/s eta 0:00:00[2025-06-01 18:21:13.218319] 

Downloading markdown_it_py-3.0.0-py3-none-any.whl (87 kB)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 87.5/87.5 kB 192.9 MB/s eta 0:00:00[2025-06-01 18:21:13.231768] 

Downloading pygments-2.19.1-py3-none-any.whl (1.2 MB)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 57.0 MB/s eta 0:00:00[2025-06-01 18:21:13.266466] 

Downloading mdurl-0.1.2-py3-none-any.whl (10.0 kB)

Installing collected packages: pygments, mdurl, markdown-it-py, rich

  Attempting uninstall: pygments

    Found existing installation: Pygments 2.19.1

    Uninstalling Pygments-2.19.1:

      Successfully uninstalled Pygments-2.19.1

  Attempting uninstall: mdurl

    Found existing installation: mdurl 0.1.2

    Uninstalling mdurl-0.1.2:

      Successfully uninstalled mdurl-0.1.2

  Attempting uninstall: markdown-it-py

    Found existing installation: markdown-it-py 3.0.0

    Uninstalling markdown-it-py-3.0.0:

      Successfully uninstalled markdown-it-py-3.0.0

  Attempting uninstall: rich

    Found existing installation: rich 14.0.0

    Uninstalling rich-14.0.0:

      Successfully uninstalled rich-14.0.0

Successfully installed markdown-it-py-3.0.0 mdurl-0.1.2 pygments-2.19.1 rich-14.0.0


[notice] A new release of pip is available: 24.0 -> 25.1.1

[notice] To update, run: pip install --upgrade pip


────────────────────────────────────────────────────────────────────────────────────────


[18:21:16] ❗️ installer returned a non-zero exit code

[20:00:32] 🐙 Pulling code changes from Github...

[20:00:32] 📦 Processing dependencies...


──────────────────────────────────────── uv ───────────────────────────────────────────


Using uv pip install.

Using Python 3.13.3 environment at /home/adminuser/venv

Resolved 52 packages in 153ms

  × Failed to download and build `pandas==2.1.0`

  ╰─▶ Build backend failed to build wheel through `build_wheel` (exit status:

      1)


      [stdout]

      + meson setup

      /home/adminuser/.cache/uv/sdists-v6/pypi/pandas/2.1.0/24_E8Vy_u96ZbaEV3GufS/src

      /home/adminuser/.cache/uv/sdists-v6/pypi/pandas/2.1.0/24_E8Vy_u96ZbaEV3GufS/src/.mesonpy-laptd0mb/build

      -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --vsenv

      --native-file=/home/adminuser/.cache/uv/sdists-v6/pypi/pandas/2.1.0/24_E8Vy_u96ZbaEV3GufS/src/.mesonpy-laptd0mb/build/meson-python-native-file.ini

      The Meson build system

      Version: 1.0.1

      Source dir:

      /home/adminuser/.cache/uv/sdists-v6/pypi/pandas/2.1.0/24_E8Vy_u96ZbaEV3GufS/src

      Build dir:

      /home/adminuser/.cache/uv/sdists-v6/pypi/pandas/2.1.0/24_E8Vy_u96ZbaEV3GufS/src/.mesonpy-laptd0mb/build

      Build type: native build

      Project name: pandas

      Project version: 2.1.0

      C compiler for the host machine: cc (gcc 10.2.1 "cc (Debian 10.2.1-6)

      10.2.1 20210110")

      C linker for the host machine: cc ld.bfd 2.35.2

      C++ compiler for the host machine: c++ (gcc 10.2.1 "c++ (Debian

      10.2.1-6) 10.2.1 20210110")

      C++ linker for the host machine: c++ ld.bfd 2.35.2

      Cython compiler for the host machine: cython (cython 0.29.37)

      Host machine cpu family: x86_64

      Host machine cpu: x86_64

      Program python found: YES

      (/home/adminuser/.cache/uv/builds-v0/.tmpLRmbWE/bin/python)

      Did not find pkg-config by name 'pkg-config'

      Found Pkg-config: NO

      Build targets in project: 53


      pandas 2.1.0


        User defined options

          Native files:

      /home/adminuser/.cache/uv/sdists-v6/pypi/pandas/2.1.0/24_E8Vy_u96ZbaEV3GufS/src/.mesonpy-laptd0mb/build/meson-python-native-file.ini

          buildtype   : release

          b_ndebug    : if-release

          b_vscrt     : md


      Found ninja-1.11.1.git.kitware.jobserver-1 at

      /home/adminuser/.cache/uv/builds-v0/.tmpLRmbWE/bin/ninja

      + /home/adminuser/.cache/uv/builds-v0/.tmpLRmbWE/bin/ninja

      [1/151] Generating pandas/_libs/algos_take_helper_pxi with a custom

      command

      [2/151] Generating pandas/_libs/khash_primitive_helper_pxi with a custom

      command

      [3/151] Generating pandas/_libs/index_class_helper_pxi with a custom

      command

      [4/151] Generating pandas/_libs/sparse_op_helper_pxi with a custom

      command

      [5/151] Generating pandas/_libs/algos_common_helper_pxi with a custom

      command

      [6/151] Generating pandas/_libs/hashtable_class_helper_pxi with a custom

      command

      [7/151] Generating pandas/_libs/intervaltree_helper_pxi with a custom

      command

      [8/151] Generating pandas/_libs/hashtable_func_helper_pxi with a custom

      command

      [9/151] Generating pandas/__init__.py with a custom command

      [10/151] Compiling Cython source

      /home/adminuser/.cache/uv/sdists-v6/pypi/pandas/2.1.0/24_E8Vy_u96ZbaEV3GufS/src/pandas/_libs/tslibs/base.pyx

      [11/151] Compiling C object

      pandas/_libs/tslibs/base.cpython-313-x86_64-linux-gnu.so.p/meson-generated_pandas__libs_tslibs_base.pyx.c.o

      FAILED:

      pandas/_libs/tslibs/base.cpython-313-x86_64-linux-gnu.so.p/meson-generated_pandas__libs_tslibs_base.pyx.c.o

      cc -Ipandas/_libs/tslibs/base.cpython-313-x86_64-linux-gnu.so.p

      -Ipandas/_libs/tslibs -I../../pandas/_libs/tslibs

      -I../../../../../../../../builds-v0/.tmpLRmbWE/lib/python3.13/site-packages/numpy/_core/include

      -I../../pandas/_libs/include -I/usr/local/include/python3.13

      -fvisibility=hidden -fdiagnostics-color=always -DNDEBUG

      -D_FILE_OFFSET_BITS=64 -w -std=c99 -O3 -DNPY_NO_DEPRECATED_API=0

      -DNPY_TARGET_VERSION=NPY_1_21_API_VERSION -fPIC -MD -MQ

      pandas/_libs/tslibs/base.cpython-313-x86_64-linux-gnu.so.p/meson-generated_pandas__libs_tslibs_base.pyx.c.o

      -MF

      pandas/_libs/tslibs/base.cpython-313-x86_64-linux-gnu.so.p/meson-generated_pandas__libs_tslibs_base.pyx.c.o.d

      -o

      pandas/_libs/tslibs/base.cpython-313-x86_64-linux-gnu.so.p/meson-generated_pandas__libs_tslibs_base.pyx.c.o

      -c

      pandas/_libs/tslibs/base.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/base.pyx.c

      pandas/_libs/tslibs/base.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/base.pyx.c:

      In function ‘__Pyx_PyInt_As_long’:

      pandas/_libs/tslibs/base.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/base.pyx.c:5397:27:

      error: too few arguments to function ‘_PyLong_AsByteArray’

       5397 |                 int ret = _PyLong_AsByteArray((PyLongObject *)v,

            |                           ^~~~~~~~~~~~~~~~~~~

      In file included from /usr/local/include/python3.13/longobject.h:107,

                       from /usr/local/include/python3.13/Python.h:81,

                       from

      pandas/_libs/tslibs/base.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/base.pyx.c:6:

      /usr/local/include/python3.13/cpython/longobject.h:111:17: note:

      declared here

        111 | PyAPI_FUNC(int) _PyLong_AsByteArray(PyLongObject* v,

            |                 ^~~~~~~~~~~~~~~~~~~

      pandas/_libs/tslibs/base.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/base.pyx.c:

      In function ‘__Pyx_PyInt_As_int’:

      pandas/_libs/tslibs/base.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/base.pyx.c:5631:27:

      error: [2025-06-01 20:00:54.550874] too few arguments to function ‘_PyLong_AsByteArray’

       5631 |                 int ret = _PyLong_AsByteArray((PyLongObject *)v,

            |                           ^~~~~~~~~~~~~~~~~~~

      In file included from /usr/local/include/python3.13/longobject.h:107,

                       from /usr/local/include/python3.13/Python.h:81,

                       from

      pandas/_libs/tslibs/base.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/base.pyx.c:6:

      /usr/local/include/python3.13/cpython/longobject.h:111:17: note:

      declared here

        111 | PyAPI_FUNC(int) _PyLong_AsByteArray(PyLongObject* v,

            |                 ^~~~~~~~~~~~~~~~~~~

      [12/151] Compiling Cython source

      /home/adminuser/.cache/uv/sdists-v6/pypi/pandas/2.1.0/24_E8Vy_u96ZbaEV3GufS/src/pandas/_libs/tslibs/ccalendar.pyx

      [13/151] Compiling Cython source

      /home/adminuser/.cache/uv/sdists-v6/pypi/pandas/2.1.0/24_E8Vy_u96ZbaEV3GufS/src/pandas/_libs/tslibs/np_datetime.pyx

      [14/151] Compiling C object

      pandas/_libs/tslibs/parsing.cpython-313-x86_64-linux-gnu.so.p/.._src_parser_tokenizer.c.o

      [15/151] Compiling Cython source

      /home/adminuser/.cache/uv/sdists-v6/pypi/pandas/2.1.0/24_E8Vy_u96ZbaEV3GufS/src/pandas/_libs/tslibs/nattype.pyx

      [16/151] Compiling Cython source

      /home/adminuser/.cache/uv/sdists-v6/pypi/pandas/2.1.0/24_E8Vy_u96ZbaEV3GufS/src/pandas/_libs/tslibs/dtypes.pyx

      [17/151] Compiling Cython source

      /home/adminuser/.cache/uv/sdists-v6/pypi/pandas/2.1.0/24_E8Vy_u96ZbaEV3GufS/src/pandas/_libs/tslibs/conversion.pyx

      [18/151] Compiling Cython source

      /home/adminuser/.cache/uv/sdists-v6/pypi/pandas/2.1.0/24_E8Vy_u96ZbaEV3GufS/src/pandas/_libs/tslibs/timezones.pyx

      [19/151] Compiling Cython source

      /home/adminuser/.cache/uv/sdists-v6/pypi/pandas/2.1.0/24_E8Vy_u96ZbaEV3GufS/src/pandas/_libs/tslibs/vectorized.pyx

      [20/151] Compiling Cython source

      /home/adminuser/.cache/uv/sdists-v6/pypi/pandas/2.1.0/24_E8Vy_u96ZbaEV3GufS/src/pandas/_libs/tslibs/offsets.pyx

      [21/151] Compiling Cython source

      /home/adminuser/.cache/uv/sdists-v6/pypi/pandas/2.1.0/24_E8Vy_u96ZbaEV3GufS/src/pandas/_libs/tslibs/parsing.pyx

      [22/151] Compiling Cython source

      /home/adminuser/.cache/uv/sdists-v6/pypi/pandas/2.1.0/24_E8Vy_u96ZbaEV3GufS/src/pandas/_libs/tslibs/timestamps.pyx

      [23/151] Compiling Cython source

      /home/adminuser/.cache/uv/sdists-v6/pypi/pandas/2.1.0/24_E8Vy_u96ZbaEV3GufS/src/pandas/_libs/tslibs/strptime.pyx

      [24/151] Compiling Cython source

      /home/adminuser/.cache/uv/sdists-v6/pypi/pandas/2.1.0/24_E8Vy_u96ZbaEV3GufS/src/pandas/_libs/tslibs/tzconversion.pyx

      [25/151] Compiling Cython source

      /home/adminuser/.cache/uv/sdists-v6/pypi/pandas/2.1.0/24_E8Vy_u96ZbaEV3GufS/src/pandas/_libs/tslibs/fields.pyx

      [26/151] Compiling Cython source

      /home/adminuser/.cache/uv/sdists-v6/pypi/pandas/2.1.0/24_E8Vy_u96ZbaEV3GufS/src/pandas/_libs/tslibs/period.pyx

      [27/151] Compiling Cython source

      /home/adminuser/.cache/uv/sdists-v6/pypi/pandas/2.1.0/24_E8Vy_u96ZbaEV3GufS/src/pandas/_libs/tslibs/timedeltas.pyx

      [28/151] Compiling Cython source

      /home/adminuser/.cache/uv/sdists-v6/pypi/pandas/2.1.0/24_E8Vy_u96ZbaEV3GufS/src/pandas/_libs/algos.pyx

      ninja: build stopped: subcommand failed.


Checking if Streamlit is installed

Found Streamlit version 1.45.1 in the environment

Installing rich for an improved exception logging

Using uv pip install.

Using Python 3.13.3 environment at /home/adminuser/venv

Audited 1 package in 2ms


────────────────────────────────────────────────────────────────────────────────────────



──────────────────────────────────────── pip ───────────────────────────────────────────


Using standard pip install.

Collecting streamlit==1.31.0 (from -r /mount/src/admacademy/requirements.txt (line 1))

────────────────────── Traceback (most recent call last) ───────────────────────

  /home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptru  

  nner/exec_code.py:121 in exec_func_with_error_handling                        

                                                                                

  /home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptru  

  nner/script_runner.py:645 in code_to_exec                                     

                                                                                

  /mount/src/admacademy/app.py:500 in <module>                                  

                                                                                

    497 │   │   completed_simulations = [sim for sim in simulations if sim['co  

    498 │   │                                                                   

    499 │   │   # Criar dados para o gráfico                                    

  ❱ 500 │   │   import plotly.express as px                                     

    501 │   │   import pandas as pd                                             

    502 │   │                                                                   

    503 │   │   if completed_simulations:                                       

────────────────────────────────────────────────────────────────────────────────

ModuleNotFoundError: No module named 'plotly'

  Downloading streamlit-1.31.0-py2.py3-none-any.whl.metadata (8.1 kB)

Collecting pandas==2.1.0 (from -r /mount/src/admacademy/requirements.txt (line 2))

  Downloading pandas-2.1.0.tar.gz (4.3 MB)

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 MB 60.5 MB/s eta 0:00:00[2025-06-01 20:00:56.643432] 

  Installing build dependencies: started

  Installing build dependencies: finished with status 'done'

  Getting requirements to build wheel: started

  Getting requirements to build wheel: finished with status 'done'

  Installing backend dependencies: started

  Installing backend dependencies: finished with status 'done'

  Preparing metadata (pyproject.toml): started

  Preparing metadata (pyproject.toml): finished with status 'error'

  error: subprocess-exited-with-error

  

  × Preparing metadata (pyproject.toml) did not run successfully.

  │ exit code: 1

  ╰─> [104 lines of output]

      + meson setup /tmp/pip-install-fcicglbj/pandas_eefc9dca14284754a95e06eb509c8ae4 /tmp/pip-install-fcicglbj/pandas_eefc9dca14284754a95e06eb509c8ae4/.mesonpy-ndn1rzzk/build -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --vsenv --native-file=/tmp/pip-install-fcicglbj/pandas_eefc9dca14284754a95e06eb509c8ae4/.mesonpy-ndn1rzzk/build/meson-python-native-file.ini

      The Meson build system

      Version: 1.0.1

      Source dir: /tmp/pip-install-fcicglbj/pandas_eefc9dca14284754a95e06eb509c8ae4

      Build dir: /tmp/pip-install-fcicglbj/pandas_eefc9dca14284754a95e06eb509c8ae4/.mesonpy-ndn1rzzk/build

      Build type: native build

      Project name: pandas

      Project version: 2.1.0

      C compiler for the host machine: cc (gcc 10.2.1 "cc (Debian 10.2.1-6) 10.2.1 20210110")

      C linker for the host machine: cc ld.bfd 2.35.2

      C++ compiler for the host machine: c++ (gcc 10.2.1 "c++ (Debian 10.2.1-6) 10.2.1 20210110")

      C++ linker for the host machine: c++ ld.bfd 2.35.2

      Cython compiler for the host machine: cython (cython 0.29.37)

      Host machine cpu family: x86_64

      Host machine cpu: x86_64

      Program python found: YES (/home/adminuser/venv/bin/python)

      Did not find pkg-config by name 'pkg-config'

      Found Pkg-config: NO

      Build targets in project: 53

      

      pandas 2.1.0

      

        User defined options

          Native files: /tmp/pip-install-fcicglbj/pandas_eefc9dca14284754a95e06eb509c8ae4/.mesonpy-ndn1rzzk/build/meson-python-native-file.ini

          buildtype   : release

          b_ndebug    : if-release

          b_vscrt     : md

      

      Found ninja-1.11.1.git.kitware.jobserver-1 at /tmp/pip-build-env-g9riwww6/normal/bin/ninja

      + /tmp/pip-build-env-g9riwww6/normal/bin/ninja

      [1/151] Generating pandas/_libs/index_class_helper_pxi with a custom command

      [2/151] Generating pandas/_libs/intervaltree_helper_pxi with a custom command

      [3/151] Generating pandas/_libs/khash_primitive_helper_pxi with a custom command

      [4/151] Generating pandas/_libs/algos_common_helper_pxi with a custom command

      [5/151] Generating pandas/_libs/sparse_op_helper_pxi with a custom command

      [6/151] Generating pandas/_libs/hashtable_class_helper_pxi with a custom command

      [7/151] Generating pandas/_libs/algos_take_helper_pxi with a custom command

      [8/151] Generating pandas/__init__.py with a custom command

      [9/151] Generating pandas/_libs/hashtable_func_helper_pxi with a custom command

      [10/151] Compiling Cython source /tmp/pip-install-fcicglbj/pandas_eefc9dca14284754a95e06eb509c8ae4/pandas/_libs/tslibs/base.pyx

      [11/151] Compiling Cython source /tmp/pip-install-fcicglbj/pandas_eefc9dca14284754a95e06eb509c8ae4/pandas/_libs/tslibs/ccalendar.pyx

      [12/151] Compiling C object pandas/_libs/tslibs/ccalendar.cpython-313-x86_64-linux-gnu.so.p/meson-generated_pandas__libs_tslibs_ccalendar.pyx.c.o

      FAILED: pandas/_libs/tslibs/ccalendar.cpython-313-x86_64-linux-gnu.so.p/meson-generated_pandas__libs_tslibs_ccalendar.pyx.c.o

      cc -Ipandas/_libs/tslibs/ccalendar.cpython-313-x86_64-linux-gnu.so.p -Ipandas/_libs/tslibs -I../../pandas/_libs/tslibs -I../../../../pip-build-env-g9riwww6/overlay/lib/python3.13/site-packages/numpy/_core/include -I../../pandas/_libs/include -I/usr/local/include/python3.13 -fvisibility=hidden -fdiagnostics-color=always -DNDEBUG -D_FILE_OFFSET_BITS=64 -w -std=c99 -O3 -DNPY_NO_DEPRECATED_API=0 -DNPY_TARGET_VERSION=NPY_1_21_API_VERSION -fPIC -MD -MQ pandas/_libs/tslibs/ccalendar.cpython-313-x86_64-linux-gnu.so.p/meson-generated_pandas__libs_tslibs_ccalendar.pyx.c.o -MF pandas/_libs/tslibs/ccalendar.cpython-313-x86_64-linux-gnu.so.p/meson-generated_pandas__libs_tslibs_ccalendar.pyx.c.o.d -o pandas/_libs/tslibs/ccalendar.cpython-313-x86_64-linux-gnu.so.p/meson-generated_pandas__libs_tslibs_ccalendar.pyx.c.o -c pandas/_libs/tslibs/ccalendar.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/ccalendar.pyx.c

      pandas/_libs/tslibs/ccalendar.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/ccalendar.pyx.c: In function ‘__Pyx_PyInt_As_int’:

      pandas/_libs/tslibs/ccalendar.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/ccalendar.pyx.c:7550:27: error: too few arguments to function ‘_PyLong_AsByteArray’

       7550 |                 int ret = _PyLong_AsByteArray((PyLongObject *)v,

            |                           ^~~~~~~~~~~~~~~~~~~

      In file included from /usr/local/include/python3.13/longobject.h:107,

                       from /usr/local/include/python3.13/Python.h:81,

                       from pandas/_libs/tslibs/ccalendar.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/ccalendar.pyx.c:6:

      /usr/local/include/python3.13/cpython/longobject.h:111:17: note: declared here

        111 | PyAPI_FUNC(int) _PyLong_AsByteArray(PyLongObject* v,

            |                 ^~~~~~~~~~~~~~~~~~~

      pandas/_libs/tslibs/ccalendar.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/ccalendar.pyx.c: In function ‘__Pyx_PyInt_As_long’:

      pandas/_libs/tslibs/ccalendar.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/ccalendar.pyx.c:7860:27: error: too few arguments to function ‘_PyLong_AsByteArray’

       7860 |                 int ret = _PyLong_AsByteArray((PyLongObject *)v,

            |                           ^~~~~~~~~~~~~~~~~~~

      In file included from /usr/local/include/python3.13/longobject.h:107,

                       from /usr/local/include/python3.13/Python.h:81,

                       from pandas/_libs/tslibs/ccalendar.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/ccalendar.pyx.c:6:

      /usr/local/include/python3.13/cpython/longobject.h:111:17: note: declared here

        111 | PyAPI_FUNC(int) _PyLong_AsByteArray(PyLongObject* v,

            |                 ^~~~~~~~~~~~~~~~~~~

      [13/151] Compiling C object pandas/_libs/tslibs/base.cpython-313-x86_64-linux-gnu.so.p/meson-generated_pandas__libs_tslibs_base.pyx.c.o

      FAILED: pandas/_libs/tslibs/base.cpython-313-x86_64-linux-gnu.so.p/meson-generated_pandas__libs_tslibs_base.pyx.c.o

      cc -Ipandas/_libs/tslibs/base.cpython-313-x86_64-linux-gnu.so.p -Ipandas/_libs/tslibs -I../../pandas/_libs/tslibs -I../../../../pip-build-env-g9riwww6/overlay/lib/python3.13/site-packages/numpy/_core/include -I../../pandas/_libs/include -I/usr/local/include/python3.13 -fvisibility=hidden -fdiagnostics-color=always -DNDEBUG -D_FILE_OFFSET_BITS=64 -w -std=c99 -O3 -DNPY_NO_DEPRECATED_API=0 -DNPY_TARGET_VERSION=NPY_1_21_API_VERSION -fPIC -MD -MQ pandas/_libs/tslibs/base.cpython-313-x86_64-linux-gnu.so.p/meson-generated_pandas__libs_tslibs_base.pyx.c.o -MF pandas/_libs/tslibs/base.cpython-313-x86_64-linux-gnu.so.p/meson-generated_pandas__libs_tslibs_base.pyx.c.o.d -o pandas/_libs/tslibs/base.cpython-313-x86_64-linux-gnu.so.p/meson-generated_pandas__libs_tslibs_base.pyx.c.o -c pandas/_libs/tslibs/base.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/base.pyx.c

      pandas/_libs/tslibs/base.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/base.pyx.c: In function ‘__Pyx_PyInt_As_long’:

      pandas/_libs/tslibs/base.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/base.pyx.c:5397:27: error: too few arguments to function ‘_PyLong_AsByteArray’

       5397 |                 int ret = _PyLong_AsByteArray((PyLongObject *)v,

            |                           ^~~~~~~~~~~~~~~~~~~

      In file included from /usr/local/include/python3.13/longobject.h:107,

                       from /usr/local/include/python3.13/Python.h:81,

                       from pandas/_libs/tslibs/base.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/base.pyx.c:6:

      /usr/local/include/python3.13/cpython/longobject.h:111:17: note: declared here

        111 | PyAPI_FUNC(int) _PyLong_AsByteArray(PyLongObject* v,

            |                 ^~~~~~~~~~~~~~~~~~~

      pandas/_libs/tslibs/base.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/base.pyx.c: In function ‘__Pyx_PyInt_As_int’:

      pandas/_libs/tslibs/base.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/base.pyx.c:5631:27: error: too few arguments to function ‘_PyLong_AsByteArray’

       5631 |                 int ret = _PyLong_AsByteArray((PyLongObject *)v,

            |                           ^~~~~~~~~~~~~~~~~~~

      In file included from /usr/local/include/python3.13/longobject.h:107,

                       from /usr/local/include/python3.13/Python.h:81,

                       from pandas/_libs/tslibs/base.cpython-313-x86_64-linux-gnu.so.p/pandas/_libs/tslibs/base.pyx.c:6:

      /usr/local/include/python3.13/cpython/longobject.h:111:17: note: declared here

        111 | PyAPI_FUNC(int) _PyLong_AsByteArray(PyLongObject* v,

            |                 ^~~~~~~~~~~~~~~~~~~

      [14/151] Compiling Cython source /tmp/pip-install-fcicglbj/pandas_eefc9dca14284754a95e06eb509c8ae4/pandas/_libs/tslibs/nattype.pyx

      [15/151] Compiling C object pandas/_libs/tslibs/parsing.cpython-313-x86_64-linux-gnu.so.p/.._src_parser_tokenizer.c.o

      [16/151] Compiling Cython source /tmp/pip-install-fcicglbj/pandas_eefc9dca14284754a95e06eb509c8ae4/pandas/_libs/tslibs/dtypes.pyx

      [17/151] Compiling Cython source /tmp/pip-install-fcicglbj/pandas_eefc9dca14284754a95e06eb509c8ae4/pandas/_libs/tslibs/np_datetime.pyx

      [18/151] Compiling Cython source /tmp/pip-install-fcicglbj/pandas_eefc9dca14284754a95e06eb509c8ae4/pandas/_libs/tslibs/timezones.pyx

      [19/151] Compiling Cython source /tmp/pip-install-fcicglbj/pandas_eefc9dca14284754a95e06eb509c8ae4/pandas/_libs/tslibs/conversion.pyx

      [20/151] Compiling Cython source /tmp/pip-install-fcicglbj/pandas_eefc9dca14284754a95e06eb509c8ae4/pandas/_libs/tslibs/fields.pyx

      [21/151] Compiling Cython source /tmp/pip-install-fcicglbj/pandas_eefc9dca14284754a95e06eb509c8ae4/pandas/_libs/tslibs/vectorized.pyx

      [22/151] Compiling Cython source /tmp/pip-install-fcicglbj/pandas_eefc9dca14284754a95e06eb509c8ae4/pandas/_libs/tslibs/offsets.pyx

      [23/151] Compiling Cython source /tmp/pip-install-fcicglbj/pandas_eefc9dca14284754a95e06eb509c8ae4/pandas/_libs/tslibs/parsing.pyx

      [24/151] Compiling Cython source /tmp/pip-install-fcicglbj/pandas_eefc9dca14284754a95e06eb509c8ae4/pandas/_libs/tslibs/strptime.pyx

      [25/151] Compiling Cython source /tmp/pip-install-fcicglbj/pandas_eefc9dca14284754a95e06eb509c8ae4/pandas/_libs/tslibs/tzconversion.pyx

      [26/151] Compiling Cython source /tmp/pip-install-fcicglbj/pandas_eefc9dca14284754a95e06eb509c8ae4/pandas/_libs/tslibs/period.pyx

      [27/151] Compiling Cython source /tmp/pip-install-fcicglbj/pandas_eefc9dca14284754a95e06eb509c8ae4/pandas/_libs/tslibs/timedeltas.pyx

      [28/151] Compiling Cython source /tmp/pip-install-fcicglbj/pandas_eefc9dca14284754a95e06eb509c8ae4/pandas/_libs/tslibs/timestamps.pyx

      [29/151] Compiling Cython source /tmp/pip-install-fcicglbj/pandas_eefc9dca14284754a95e06eb509c8ae4/pandas/_libs/algos.pyx

      ninja: build stopped: subcommand failed.

      [end of output]

  

  note: This error originates from a subprocess, and is likely not a problem with pip.

error: metadata-generation-failed


× Encountered error while generating package metadata.

╰─> See above for output.


note: This is an issue with the package mentioned above, not pip.

hint: See above for details.

────────────────────── Traceback (most recent call last) ───────────────────────

  /home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptru  

  nner/exec_code.py:121 in exec_func_with_error_handling                        

                                                                                

  /home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptru  

  nner/script_runner.py:645 in code_to_exec                                     

                                                                                

  /mount/src/admacademy/app.py:500 in <module>                                  

                                                                                

    497 │   │   │   │   │   index=0                                             

    498 │   │   │   │   )                                                       

    499 │   │   │   │   if st.button("Configurar Serviço de Nuvem"):            

  ❱ 500 │   │   │   │   │   if cloud_service == "Google Drive":                 

    501 │   │   │   │   │   │   CLOUD_STORAGE_TYPE = "gdrive"                   

    502 │   │   │   │   │   elif cloud_service == "Dropbox":                    

    503 │   │   │   │   │   │   CLOUD_STORAGE_TYPE = "dropbox"                  

────────────────────────────────────────────────────────────────────────────────

ModuleNotFoundError: No module named 'plotly'


[notice] A new release of pip is available: 24.0 -> 25.1.1

[notice] To update, run: pip install --upgrade pip

Checking if Streamlit is installed

Found Streamlit version 1.45.1 in the environment

Installing rich for an improved exception logging

Using standard pip install.

Collecting rich>=10.14.0

  Downloading rich-14.0.0-py3-none-any.whl.metadata (18 kB)

Collecting markdown-it-py>=2.2.0 (from rich>=10.14.0)

  Downloading markdown_it_py-3.0.0-py3-none-any.whl.metadata (6.9 kB)

Collecting pygments<3.0.0,>=2.13.0 (from rich>=10.14.0)

  Downloading pygments-2.19.1-py3-none-any.whl.metadata (2.5 kB)

Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich>=10.14.0)

  Downloading mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)

Downloading rich-14.0.0-py3-none-any.whl (243 kB)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 243.2/243.2 kB 12.8 MB/s eta 0:00:00[2025-06-01 20:01:27.828286] 

Downloading markdown_it_py-3.0.0-py3-none-any.whl (87 kB)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 87.5/87.5 kB 144.9 MB/s eta 0:00:00[2025-06-01 20:01:27.840785] 

Downloading pygments-2.19.1-py3-none-any.whl (1.2 MB)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 62.9 MB/s eta 0:00:00[2025-06-01 20:01:27.873542] 

Downloading mdurl-0.1.2-py3-none-any.whl (10.0 kB)

Installing collected packages: pygments, mdurl, markdown-it-py, rich

  Attempting uninstall: pygments

    Found existing installation: Pygments 2.19.1

    Uninstalling Pygments-2.19.1:

      Successfully uninstalled Pygments-2.19.1

  Attempting uninstall: mdurl

    Found existing installation: mdurl 0.1.2

    Uninstalling mdurl-0.1.2:

      Successfully uninstalled mdurl-0.1.2

  Attempting uninstall: markdown-it-py

    Found existing installation: markdown-it-py 3.0.0

    Uninstalling markdown-it-py-3.0.0:

      Successfully uninstalled markdown-it-py-3.0.0

  Attempting uninstall: rich

    Found existing installation: rich 14.0.0

    Uninstalling rich-14.0.0:

      Successfully uninstalled rich-14.0.0

Successfully installed markdown-it-py-3.0.0 mdurl-0.1.2 pygments-2.19.1 rich-14.0.0


[notice] A new release of pip is available: 24.0 -> 25.1.1

[notice] To update, run: pip install --upgrade pip


────────────────────────────────────────────────────────────────────────────────────────


[20:01:30] ❗️ installer returned a non-zero exit code

────────────────────── Traceback (most recent call last) ───────────────────────

  /home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptru  

  nner/exec_code.py:121 in exec_func_with_error_handling                        

                                                                                

  /home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptru  

  nner/script_runner.py:645 in code_to_exec                                     

                                                                                

  /mount/src/admacademy/app.py:500 in <module>                                  

                                                                                

    497 │   │   │   │   │   index=0                                             

    498 │   │   │   │   )                                                       

    499 │   │   │   │   if st.button("Configurar Serviço de Nuvem"):            

  ❱ 500 │   │   │   │   │   if cloud_service == "Google Drive":                 

    501 │   │   │   │   │   │   CLOUD_STORAGE_TYPE = "gdrive"                   

    502 │   │   │   │   │   elif cloud_service == "Dropbox":                    

    503 │   │   │   │   │   │   CLOUD_STORAGE_TYPE = "dropbox"                  

────────────────────────────────────────────────────────────────────────────────

ModuleNotFoundError: No module named 'plotly'

main
